rootUser: minioadmin
rootPassword: minioadmin
mode: standalone
replicas: 1
resources:
  requests:
    memory: 256Mi
buckets:
  - name: drone-detection
  - name: mlflow
persistence:
  size: 10Gi
consoleIngress:
  enabled: false
