apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-detection-api
  labels:
    app: drone-detection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-detection-api
  template:
    metadata:
      labels:
        app: drone-detection-api
    spec:
      containers:
        - name: api
          image: europe-west1-docker.pkg.dev/gen-lang-client-0325944995/drone-detection/api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio:9000"
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: drone-detection-api
spec:
  selector:
    app: drone-detection-api
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
